# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from motor_control/comand_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class comand_msg(genpy.Message):
  _md5sum = "a0046743715cfd63f29b50134bc02d4f"
  _type = "motor_control/comand_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 motor
uint32 position
bool direction
"""
  __slots__ = ['motor','position','direction']
  _slot_types = ['uint8','uint32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor,position,direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(comand_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motor is None:
        self.motor = 0
      if self.position is None:
        self.position = 0
      if self.direction is None:
        self.direction = False
    else:
      self.motor = 0
      self.position = 0
      self.direction = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_BIB.pack(_x.motor, _x.position, _x.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.motor, _x.position, _x.direction,) = _struct_BIB.unpack(str[start:end])
      self.direction = bool(self.direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_BIB.pack(_x.motor, _x.position, _x.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.motor, _x.position, _x.direction,) = _struct_BIB.unpack(str[start:end])
      self.direction = bool(self.direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_BIB = struct.Struct("<BIB")
