// Generated by gencpp from file motor_control/comand_msg_1.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_COMAND_MSG_1_H
#define MOTOR_CONTROL_MESSAGE_COMAND_MSG_1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control
{
template <class ContainerAllocator>
struct comand_msg_1_
{
  typedef comand_msg_1_<ContainerAllocator> Type;

  comand_msg_1_()
    : motor(0)
    , position(0)  {
    }
  comand_msg_1_(const ContainerAllocator& _alloc)
    : motor(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef uint32_t _motor_type;
  _motor_type motor;

   typedef int32_t _position_type;
  _position_type position;




  typedef boost::shared_ptr< ::motor_control::comand_msg_1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::comand_msg_1_<ContainerAllocator> const> ConstPtr;

}; // struct comand_msg_1_

typedef ::motor_control::comand_msg_1_<std::allocator<void> > comand_msg_1;

typedef boost::shared_ptr< ::motor_control::comand_msg_1 > comand_msg_1Ptr;
typedef boost::shared_ptr< ::motor_control::comand_msg_1 const> comand_msg_1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::comand_msg_1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::comand_msg_1_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_control': ['/home/rics/workspace/src/motor_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::comand_msg_1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::comand_msg_1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::comand_msg_1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::comand_msg_1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::comand_msg_1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::comand_msg_1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::comand_msg_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6af2c4945f1f8a63edc4ddc639177775";
  }

  static const char* value(const ::motor_control::comand_msg_1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6af2c4945f1f8a63ULL;
  static const uint64_t static_value2 = 0xedc4ddc639177775ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::comand_msg_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/comand_msg_1";
  }

  static const char* value(const ::motor_control::comand_msg_1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::comand_msg_1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 motor\n\
int32 position\n\
";
  }

  static const char* value(const ::motor_control::comand_msg_1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::comand_msg_1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct comand_msg_1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::comand_msg_1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::comand_msg_1_<ContainerAllocator>& v)
  {
    s << indent << "motor: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.motor);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_COMAND_MSG_1_H
