// Generated by gencpp from file motor_control/jointState.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_JOINTSTATE_H
#define MOTOR_CONTROL_MESSAGE_JOINTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control
{
template <class ContainerAllocator>
struct jointState_
{
  typedef jointState_<ContainerAllocator> Type;

  jointState_()
    : motorID(0)
    , position(0)
    , velocity(0)  {
    }
  jointState_(const ContainerAllocator& _alloc)
    : motorID(0)
    , position(0)
    , velocity(0)  {
  (void)_alloc;
    }



   typedef int32_t _motorID_type;
  _motorID_type motorID;

   typedef int32_t _position_type;
  _position_type position;

   typedef int32_t _velocity_type;
  _velocity_type velocity;




  typedef boost::shared_ptr< ::motor_control::jointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::jointState_<ContainerAllocator> const> ConstPtr;

}; // struct jointState_

typedef ::motor_control::jointState_<std::allocator<void> > jointState;

typedef boost::shared_ptr< ::motor_control::jointState > jointStatePtr;
typedef boost::shared_ptr< ::motor_control::jointState const> jointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::jointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::jointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_control': ['/home/rics/workspace/src/motor_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::jointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::jointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::jointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::jointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::jointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::jointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::jointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa45440f976b0e07d9ca47f3b33e704f";
  }

  static const char* value(const ::motor_control::jointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa45440f976b0e07ULL;
  static const uint64_t static_value2 = 0xd9ca47f3b33e704fULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::jointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/jointState";
  }

  static const char* value(const ::motor_control::jointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::jointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 motorID\n\
int32 position\n\
int32 velocity\n\
";
  }

  static const char* value(const ::motor_control::jointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::jointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorID);
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct jointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::jointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::jointState_<ContainerAllocator>& v)
  {
    s << indent << "motorID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motorID);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_JOINTSTATE_H
